### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [kba/makefile-parser#2]
Hi, what is the current status of this project? Is it still maintained?

**Comment by kba** [comment]
I use it daily for [self-documenting makefiles](https://github.com/kba/makefile-parser/blob/master/README.md#make-help) in combination with https://github.com/kba/shinclude. Since that is the only use case I have atm and works as intended, I did not have to fix anything in a while. But if you have another use case and want to extend it (e.g. directives, functions, parsing quirks, special targets like .phony etc.) I'll be happy to accept contributions.

**Comment by DanielRuf** [comment]
Would like to see some CI setup (Travis CI for example). Which CI platform do you prefer?

**Comment by kba** [comment]
Circle CI (fast, docker based, easier to debug etc.) the unit tests are minimal currently though...

**Comment by DanielRuf** [comment]
> the unit tests are minimal currently

Better than nothing.
